apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy260624
  labels:
    app: autodeploy260624
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719392894027
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy260624
  template:
    metadata:
      labels:
        app: autodeploy260624
    spec:
      containers:
        - name: autodeploy260624
          image: acrworkflow1719392894027.azurecr.io/image-workflow-1719392894027:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
