apiVersion: v1
kind: Service
metadata:
  name: autodeploy260624
  namespace: namespace-workflow-1719392894027
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy260624
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000